# Generated by Django 5.0 on 2024-01-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
